image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

build:
  stage: build
  tags: 
    - docker
  script:
    - yarn && yarn compile
    - yarn package
  only:
    - merge_requests    
  artifacts:
    paths:
      - "*.vsix"
