name: auto upd version
on:
  push:
    branches:
      - main
      - 2022.1_new_features
    paths:
      - '**.ts'
  pull_request:
    branches:
      - main
      - 2022.1_new_features
    paths:
      - '**.ts'
  workflow_dispatch:

jobs:
  build-extensions:
    runs-on: [self-hosted, linux]
    container: node:14-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update version of extension
        run: |
          npm --no-git-tag-version version patch
          git config user.name ci
          git config user.email cd4iss@intel.com
          git commit -a -m "auto upd version"
          git push
      - name: Build the package
        run: yarn install  && yarn package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: environment-extension
          path: ./*.vsix
